// src/screens/settings/HelpScreen.js
import React, { useRef, useEffect, useState } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, Animated,
  StatusBar, ScrollView, TextInput, Dimensions,
} from 'react-native';
import { useNavigation } from '@react-navigation/native';

const { width: W, height: H } = Dimensions.get('window');

const C = {
  bg:         '#0F0500',
  bgCard:     '#1A0A02',
  bgCard2:    '#200E03',
  bgInput:    '#1E0D03',
  border:     'rgba(200,134,10,0.20)',
  borderFocus:'#C8860A',
  gold:       '#C8860A',
  goldPale:   'rgba(200,134,10,0.13)',
  goldStrong: 'rgba(200,134,10,0.25)',
  cream:      '#F5DEB3',
  creamDim:   'rgba(245,222,179,0.55)',
  creamFaint: 'rgba(245,222,179,0.18)',
  success:    '#5DBE8A',
  successPale:'rgba(93,190,138,0.10)',
};

// ── FAQ data ──────────────────────────────────────────────────
const FAQ_CATEGORIES = [
  {
    id:       'scanning',
    icon:     '◉',
    label:    'Scanning',
    color:    '#C8860A',
    questions:[
      {
        q:'How do I get the most accurate scan?',
        a:'Find neutral daylight or a well-lit indoor space. Remove heavy makeup, position your face fully within the oval guide, and hold still. Avoid harsh direct sunlight which creates shadows that affect accuracy.',
      },
      {
        q:'Why does my scan keep failing?',
        a:'Ensure camera permission is granted in your device Settings → Melanin Scan → Camera. Check that lighting is adequate — too dark or too bright can cause errors. Restart the app if issues persist.',
      },
      {
        q:'How often should I scan?',
        a:'We recommend scanning once a month to track meaningful progress. Daily scanning won\'t show enough change and may not add value. The Progress tab shows trends across your scan history.',
      },
      {
        q:'Can I use the rear camera to scan?',
        a:'Yes. Go to Settings → Scan Settings → Camera and switch to Rear Camera. However, front camera typically works better as it\'s easier to position your face accurately.',
      },
      {
        q:'My skin looks different in the scan photo — is that normal?',
        a:'Yes. Camera lenses and screen colour calibration differ from how your eyes perceive your skin. The AI analyses patterns and characteristics rather than exact colours, so results are still accurate.',
      },
    ],
  },
  {
    id:       'results',
    icon:     '◈',
    label:    'Results & Analysis',
    color:    '#5DBE8A',
    questions:[
      {
        q:'What does my skin score mean?',
        a:'Your skin score (0–100) is a composite measure of hydration, clarity, evenness, texture, and overall glow based on your scan. It\'s a relative indicator for tracking your progress — not a medical rating.',
      },
      {
        q:'Why does the AI say I have hyperpigmentation?',
        a:'Post-inflammatory hyperpigmentation (PIH) is extremely common in melanin-rich skin and shows as darker patches, often from past acne or irritation. The AI identifies surface-level discolouration patterns. This is cosmetic observation, not a diagnosis.',
      },
      {
        q:'How accurate are the results?',
        a:'Our AI is trained on thousands of images specifically including melanin-rich skin tones. Accuracy improves with good lighting and clear photos. All results are cosmetic observations — consult a dermatologist for medical assessments.',
      },
      {
        q:'Can I share my scan report?',
        a:'Yes. From the Scan Results screen, tap the share icon (↗) in the top right. You can export a full PDF-style report via the "View Full Report" button, then share via WhatsApp, email, or save to your device.',
      },
      {
        q:'Why are some conditions showing as "Mild" when I can clearly see them?',
        a:'Severity reflects visible surface characteristics in the image, not how it feels to you. Lighting, image resolution, and skin texture depth all affect detection. If a condition feels significant, always consult a professional.',
      },
    ],
  },
  {
    id:       'routine',
    icon:     '✦',
    label:    'Routines & Products',
    color:    '#E8A020',
    questions:[
      {
        q:'Where do my routine recommendations come from?',
        a:'Your routine is generated by our AI based on your detected skin type, conditions, and melanin-specific needs. Ingredient choices prioritise safety and efficacy for darker skin tones, specifically avoiding triggers for PIH.',
      },
      {
        q:'Can I customise my routine?',
        a:'Routine customisation is coming in a future update. For now, you can update your skin concerns in Profile → Skin Concerns, then take a new scan to regenerate a revised routine.',
      },
      {
        q:'The products in my routine aren\'t available near me — what do I do?',
        a:'All product recommendations include common alternatives. Look for any product containing the key ingredients listed (e.g. Niacinamide 5-10%, Alpha Arbutin 2%). The ingredient is more important than the brand.',
      },
      {
        q:'Why is SPF always in my routine?',
        a:'SPF is non-negotiable for melanin skin. Even though melanin provides some UV protection, UV exposure significantly worsens hyperpigmentation, dark spots, and post-inflammatory marks. SPF 30–50 daily is essential.',
      },
    ],
  },
  {
    id:       'account',
    icon:     '◎',
    label:    'Account & Billing',
    color:    '#7B6DC8',
    questions:[
      {
        q:'How do I cancel my subscription?',
        a:'Go to Profile → Subscription Plan → Manage Subscription. Tap "Cancel Plan". Your access continues until the end of your current billing period. No refunds are issued for partial periods.',
      },
      {
        q:'Can I get a refund?',
        a:'Refunds are reviewed case-by-case. Contact support at support@melaninscan.com within 7 days of charge with your account email and reason. Refunds are not guaranteed after 7 days.',
      },
      {
        q:'I was charged but my plan didn\'t activate — what do I do?',
        a:'First, pull down to refresh on the Profile screen. If still showing Free Plan after 5 minutes, contact support immediately at support@melaninscan.com with your payment receipt and account email.',
      },
      {
        q:'Can I use one account on multiple devices?',
        a:'Yes. Your account syncs across devices when you sign in with the same email. Elite Plan includes a Family Account feature allowing up to 3 separate profiles under one subscription.',
      },
      {
        q:'How do I change my email address?',
        a:'Go to Settings → Edit Profile → Email. You\'ll receive a verification link to both your old and new email. The change takes effect once confirmed.',
      },
    ],
  },
  {
    id:       'privacy',
    icon:     '🛡',
    label:    'Privacy & Data',
    color:    '#E05C3A',
    questions:[
      {
        q:'Do you store my facial images?',
        a:'Only if you\'ve enabled "Store Scan History" in Privacy Settings. If disabled, images are processed in memory and immediately discarded after analysis. You can delete all stored images anytime from Privacy → Delete All Scan Data.',
      },
      {
        q:'Is my skin analysis data sold to third parties?',
        a:'Never. We do not sell personal data. With your opt-in consent only, anonymised and de-identified data may be used to improve our AI models. You can opt out at any time in Privacy Settings.',
      },
      {
        q:'How does Melanin Scan comply with NDPR?',
        a:'We comply with the Nigeria Data Protection Regulation. You have the right to access, correct, or delete your data at any time. Our full Privacy Policy is available at melaninscan.com/privacy.',
      },
    ],
  },
];

// ── African background ────────────────────────────────────────
function AfricanBG({ children }) {
  return (
    <View style={{ flex:1, backgroundColor:C.bg }}>
      <View style={[ab.b,{ width:440,height:440,borderRadius:220,backgroundColor:'#6B3000',opacity:0.09,top:-140,left:-110 }]} />
      <View style={[ab.b,{ width:300,height:300,borderRadius:150,backgroundColor:C.gold,opacity:0.04,bottom:-80,right:-80 }]} />
      <View style={[ab.stripe,{ top:H*0.07 }]} />
      {[{top:H*0.11,left:W*0.06,o:0.20},{top:H*0.82,left:W*0.88,o:0.13}].map((d,i)=>(
        <View key={i} style={[ab.dot,{top:d.top,left:d.left,opacity:d.o}]}/>
      ))}
      {children}
    </View>
  );
}
const ab = StyleSheet.create({
  b:     { position:'absolute' },
  stripe:{ position:'absolute',width:W,height:1.5,backgroundColor:'rgba(200,134,10,0.11)' },
  dot:   { position:'absolute',width:5,height:5,borderRadius:2.5,backgroundColor:C.gold },
});

// ── FadeSlide ─────────────────────────────────────────────────
function FadeSlide({ delay=0, from=16, children, style }) {
  const op = useRef(new Animated.Value(0)).current;
  const ty = useRef(new Animated.Value(from)).current;
  useEffect(()=>{
    Animated.parallel([
      Animated.timing(op,{toValue:1,duration:480,delay,useNativeDriver:true}),
      Animated.spring(ty,{toValue:0,friction:8,tension:50,delay,useNativeDriver:true}),
    ]).start();
  },[]);
  return <Animated.View style={[{opacity:op,transform:[{translateY:ty}]},style]}>{children}</Animated.View>;
}

function BackButton({ onPress }) {
  return (
    <TouchableOpacity style={{ position:'absolute',top:56,left:22,zIndex:99 }} onPress={onPress} activeOpacity={0.8}>
      <View style={{ width:42,height:42,borderRadius:12,backgroundColor:C.goldPale,borderWidth:1,borderColor:C.border,alignItems:'center',justifyContent:'center' }}>
        <Text style={{ color:C.cream,fontSize:18 }}>←</Text>
      </View>
    </TouchableOpacity>
  );
}

// ── Search bar ────────────────────────────────────────────────
function SearchBar({ value, onChange }) {
  const [focused, setFocused] = useState(false);
  const borderAnim = useRef(new Animated.Value(0)).current;

  const onFocus = () => {
    setFocused(true);
    Animated.timing(borderAnim,{toValue:1,duration:200,useNativeDriver:false}).start();
  };
  const onBlur  = () => {
    setFocused(false);
    Animated.timing(borderAnim,{toValue:0,duration:200,useNativeDriver:false}).start();
  };

  const borderColor = borderAnim.interpolate({
    inputRange:[0,1], outputRange:[C.border, C.borderFocus],
  });

  return (
    <Animated.View style={[sb.wrap, { borderColor }]}>
      <Text style={sb.searchIcon}>⌕</Text>
      <TextInput
        style={sb.input}
        value={value}
        onChangeText={onChange}
        placeholder="Search help articles..."
        placeholderTextColor={C.creamFaint}
        onFocus={onFocus}
        onBlur={onBlur}
        autoCorrect={false}
      />
      {value.length > 0 && (
        <TouchableOpacity onPress={()=>onChange('')}>
          <Text style={sb.clear}>✕</Text>
        </TouchableOpacity>
      )}
    </Animated.View>
  );
}
const sb = StyleSheet.create({
  wrap:      { flexDirection:'row',alignItems:'center',gap:10,backgroundColor:C.bgInput,borderWidth:1.5,borderRadius:14,paddingHorizontal:16,paddingVertical:13,marginBottom:24 },
  searchIcon:{ color:C.gold,fontSize:18,fontWeight:'700' },
  input:     { flex:1,color:C.cream,fontSize:15,paddingVertical:0 },
  clear:     { color:C.creamDim,fontSize:14,fontWeight:'700',paddingLeft:4 },
});

// ── Category tab ──────────────────────────────────────────────
function CategoryTab({ cat, active, onPress }) {
  const bg = useRef(new Animated.Value(active?1:0)).current;
  useEffect(()=>{
    Animated.timing(bg,{toValue:active?1:0,duration:220,useNativeDriver:false}).start();
  },[active]);
  const bgColor = bg.interpolate({inputRange:[0,1],outputRange:[C.bgCard,`${cat.color}18`]});
  const bdColor = bg.interpolate({inputRange:[0,1],outputRange:[C.border,`${cat.color}50`]});

  return (
    <TouchableOpacity onPress={onPress} activeOpacity={0.8}>
      <Animated.View style={[ct.tab,{backgroundColor:bgColor,borderColor:bdColor}]}>
        <Text style={ct.icon}>{cat.icon}</Text>
        <Text style={[ct.label,{color:active?cat.color:C.creamDim}]}>{cat.label}</Text>
      </Animated.View>
    </TouchableOpacity>
  );
}
const ct = StyleSheet.create({
  tab:   { flexDirection:'row',alignItems:'center',gap:6,borderWidth:1.5,borderRadius:20,paddingHorizontal:14,paddingVertical:8,marginRight:8 },
  icon:  { fontSize:13 },
  label: { fontSize:12,fontWeight:'700' },
});

// ── FAQ item ──────────────────────────────────────────────────
function FAQItem({ q, a, catColor, index, isSearchResult=false }) {
  const [open, setOpen] = useState(isSearchResult); // auto-expand search results
  const expandH   = useRef(new Animated.Value(isSearchResult?1:0)).current;
  const rotateAnim= useRef(new Animated.Value(isSearchResult?1:0)).current;

  const toggle = () => {
    setOpen(o => {
      Animated.parallel([
        Animated.timing(expandH,   {toValue:o?0:1,duration:280,useNativeDriver:false}),
        Animated.timing(rotateAnim,{toValue:o?0:1,duration:280,useNativeDriver:true}),
      ]).start();
      return !o;
    });
  };

  const rotate = rotateAnim.interpolate({inputRange:[0,1],outputRange:['0deg','180deg']});
  const color  = catColor || C.gold;

  return (
    <FadeSlide delay={index*50} style={{ marginBottom:8 }}>
      <View style={[fi.card, open && {borderColor:`${color}35`}]}>
        <TouchableOpacity onPress={toggle} style={fi.qRow} activeOpacity={0.8}>
          <View style={[fi.qDot,{backgroundColor:color}]}/>
          <Text style={fi.q}>{q}</Text>
          <Animated.Text style={[fi.chevron,{transform:[{rotate}],color}]}>▾</Animated.Text>
        </TouchableOpacity>
        {/* Answer */}
        <Animated.View style={{
          maxHeight:expandH.interpolate({inputRange:[0,1],outputRange:[0,300]}),
          overflow:'hidden',
          opacity:expandH.interpolate({inputRange:[0,0.3,1],outputRange:[0,0,1]}),
        }}>
          <View style={fi.aWrap}>
            <Text style={fi.a}>{a}</Text>
            <TouchableOpacity style={fi.helpfulRow}>
              <Text style={fi.helpfulText}>Was this helpful?</Text>
              <TouchableOpacity style={fi.helpfulBtn}><Text style={fi.helpfulBtnText}>👍 Yes</Text></TouchableOpacity>
              <TouchableOpacity style={fi.helpfulBtn}><Text style={fi.helpfulBtnText}>👎 No</Text></TouchableOpacity>
            </TouchableOpacity>
          </View>
        </Animated.View>
      </View>
    </FadeSlide>
  );
}
const fi = StyleSheet.create({
  card:       { backgroundColor:C.bgCard,borderWidth:1,borderColor:C.border,borderRadius:14,overflow:'hidden' },
  qRow:       { flexDirection:'row',alignItems:'flex-start',gap:10,padding:15 },
  qDot:       { width:5,height:5,borderRadius:2.5,marginTop:7,flexShrink:0 },
  q:          { flex:1,color:C.cream,fontSize:14,fontWeight:'600',lineHeight:20 },
  chevron:    { fontSize:14,fontWeight:'700',marginTop:2 },
  aWrap:      { borderTopWidth:1,borderTopColor:C.border,padding:15 },
  a:          { color:C.creamDim,fontSize:13,lineHeight:21,marginBottom:14 },
  helpfulRow: { flexDirection:'row',alignItems:'center',gap:8 },
  helpfulText:{ color:C.creamFaint,fontSize:11,flex:1 },
  helpfulBtn: { backgroundColor:C.bgCard2,borderWidth:1,borderColor:C.border,borderRadius:8,paddingHorizontal:10,paddingVertical:5 },
  helpfulBtnText:{ color:C.creamDim,fontSize:11,fontWeight:'600' },
});

// ── Contact card ──────────────────────────────────────────────
function ContactCard({ icon, title, subtitle, cta, onPress, accentColor, delay }) {
  const scale = useRef(new Animated.Value(1)).current;
  const acc   = accentColor || C.gold;
  return (
    <FadeSlide delay={delay} style={{ flex:1 }}>
      <TouchableOpacity
        onPress={onPress} activeOpacity={0.85}
        onPressIn={()=>Animated.spring(scale,{toValue:0.96,useNativeDriver:true}).start()}
        onPressOut={()=>Animated.spring(scale,{toValue:1,useNativeDriver:true}).start()}
      >
        <Animated.View style={[cc.card,{borderColor:`${acc}30`,transform:[{scale}]}]}>
          <View style={[cc.iconBox,{backgroundColor:`${acc}14`,borderColor:`${acc}30`}]}>
            <Text style={{fontSize:20}}>{icon}</Text>
          </View>
          <Text style={cc.title}>{title}</Text>
          <Text style={cc.subtitle}>{subtitle}</Text>
          <View style={[cc.cta,{backgroundColor:`${acc}14`,borderColor:`${acc}35`}]}>
            <Text style={[cc.ctaText,{color:acc}]}>{cta}</Text>
          </View>
        </Animated.View>
      </TouchableOpacity>
    </FadeSlide>
  );
}
const cc = StyleSheet.create({
  card:    { backgroundColor:C.bgCard,borderWidth:1,borderRadius:16,padding:16,alignItems:'center',gap:8 },
  iconBox: { width:50,height:50,borderRadius:14,borderWidth:1,alignItems:'center',justifyContent:'center',marginBottom:4 },
  title:   { color:C.cream,fontSize:14,fontWeight:'800',textAlign:'center' },
  subtitle:{ color:C.creamDim,fontSize:11,textAlign:'center',lineHeight:17 },
  cta:     { borderWidth:1,borderRadius:8,paddingHorizontal:14,paddingVertical:7,marginTop:4 },
  ctaText: { fontSize:11,fontWeight:'700',letterSpacing:0.5 },
});

// ── Video tutorial card ───────────────────────────────────────
function TutorialCard({ icon, title, duration, delay }) {
  const scale = useRef(new Animated.Value(1)).current;
  return (
    <FadeSlide delay={delay} style={{ marginBottom:8 }}>
      <TouchableOpacity
        activeOpacity={0.85}
        onPressIn={()=>Animated.spring(scale,{toValue:0.97,useNativeDriver:true}).start()}
        onPressOut={()=>Animated.spring(scale,{toValue:1,useNativeDriver:true}).start()}
      >
        <Animated.View style={[tc2.card,{transform:[{scale}]}]}>
          <View style={tc2.playBox}>
            <Text style={{color:C.gold,fontSize:16}}>▶</Text>
          </View>
          <View style={{flex:1}}>
            <Text style={tc2.title}>{title}</Text>
            <Text style={tc2.duration}>{duration}</Text>
          </View>
          <Text style={{color:C.creamFaint,fontSize:18,fontWeight:'300',lineHeight:20}}>›</Text>
        </Animated.View>
      </TouchableOpacity>
    </FadeSlide>
  );
}
const tc2 = StyleSheet.create({
  card:    { flexDirection:'row',alignItems:'center',gap:14,backgroundColor:C.bgCard,borderWidth:1,borderColor:C.border,borderRadius:14,padding:14 },
  playBox: { width:42,height:42,borderRadius:10,backgroundColor:C.goldPale,borderWidth:1,borderColor:C.border,alignItems:'center',justifyContent:'center' },
  title:   { color:C.cream,fontSize:13,fontWeight:'600',marginBottom:3 },
  duration:{ color:C.creamDim,fontSize:11 },
});

// ── Screen ────────────────────────────────────────────────────
export default function HelpScreen() {
  const navigation = useNavigation();
  const [query,       setQuery]       = useState('');
  const [activeCategory, setActiveCategory] = useState(FAQ_CATEGORIES[0].id);

  // Build flat list for search
  const allQA = FAQ_CATEGORIES.flatMap(cat =>
    cat.questions.map(q => ({ ...q, catColor:cat.color, catIcon:cat.icon, catLabel:cat.label }))
  );

  const searchResults = query.trim().length > 1
    ? allQA.filter(item =>
        item.q.toLowerCase().includes(query.toLowerCase()) ||
        item.a.toLowerCase().includes(query.toLowerCase())
      )
    : null;

  const activeCat = FAQ_CATEGORIES.find(c=>c.id===activeCategory);

  return (
    <AfricanBG>
      <StatusBar barStyle="light-content" backgroundColor="transparent" translucent />
      <BackButton onPress={()=>navigation.goBack()} />

      <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">

        {/* Header */}
        <FadeSlide delay={0} style={s.header}>
          <View style={s.helpBadge}>
            <Text style={s.helpBadgeIcon}>◎</Text>
          </View>
          <Text style={s.title}>Help Centre</Text>
          <Text style={s.subtitle}>
            Find answers about scanning, results, routines, and your account.
          </Text>
        </FadeSlide>

        {/* Search */}
        <FadeSlide delay={100}>
          <SearchBar value={query} onChange={setQuery} />
        </FadeSlide>

        {/* ── Search results ── */}
        {searchResults !== null && (
          <>
            <FadeSlide delay={0} style={s.searchResultsHeader}>
              <View style={s.searchResultsDot}/>
              <Text style={s.searchResultsLabel}>
                {searchResults.length} result{searchResults.length!==1?'s':''} for "{query}"
              </Text>
            </FadeSlide>

            {searchResults.length === 0 ? (
              <FadeSlide delay={80} style={s.noResults}>
                <Text style={s.noResultsIcon}>◎</Text>
                <Text style={s.noResultsTitle}>No results found</Text>
                <Text style={s.noResultsText}>
                  Try different keywords, or contact our support team below.
                </Text>
              </FadeSlide>
            ) : (
              searchResults.map((item,i)=>(
                <View key={i}>
                  <View style={s.searchCatLabel}>
                    <Text style={{color:item.catColor,fontSize:12,fontWeight:'700'}}>{item.catIcon}  {item.catLabel}</Text>
                  </View>
                  <FAQItem q={item.q} a={item.a} catColor={item.catColor} index={i} isSearchResult />
                </View>
              ))
            )}
          </>
        )}

        {/* ── Normal browse mode ── */}
        {searchResults === null && (
          <>
            {/* Category tabs */}
            <FadeSlide delay={150}>
              <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.categoryScroll}>
                {FAQ_CATEGORIES.map(cat=>(
                  <CategoryTab
                    key={cat.id}
                    cat={cat}
                    active={activeCategory===cat.id}
                    onPress={()=>setActiveCategory(cat.id)}
                  />
                ))}
              </ScrollView>
            </FadeSlide>

            {/* FAQ list */}
            <FadeSlide delay={200} style={s.catHeader}>
              <View style={[s.catIconBig,{backgroundColor:`${activeCat.color}18`,borderColor:`${activeCat.color}35`}]}>
                <Text style={{fontSize:20}}>{activeCat.icon}</Text>
              </View>
              <View>
                <Text style={s.catTitle}>{activeCat.label}</Text>
                <Text style={s.catCount}>{activeCat.questions.length} articles</Text>
              </View>
            </FadeSlide>

            {activeCat.questions.map((item,i)=>(
              <FAQItem
                key={i}
                q={item.q}
                a={item.a}
                catColor={activeCat.color}
                index={i}
              />
            ))}

            {/* Video tutorials */}
            <FadeSlide delay={400} style={s.sectionWrap}>
              <View style={s.sectionRow}>
                <View style={s.sectionBar}/>
                <Text style={s.sectionTitle}>Video Tutorials</Text>
              </View>
              <TutorialCard icon="▶" title="How to take your first skin scan"       duration="2 min 14 sec" delay={430} />
              <TutorialCard icon="▶" title="Understanding your scan results"         duration="3 min 42 sec" delay={480} />
              <TutorialCard icon="▶" title="Reading your melanin insights"           duration="2 min 55 sec" delay={530} />
              <TutorialCard icon="▶" title="Following your AM & PM routine"          duration="4 min 08 sec" delay={580} />
              <TutorialCard icon="▶" title="Tracking your skin progress over time"   duration="1 min 58 sec" delay={630} />
            </FadeSlide>

            {/* Contact options */}
            <FadeSlide delay={680} style={s.sectionWrap}>
              <View style={s.sectionRow}>
                <View style={s.sectionBar}/>
                <Text style={s.sectionTitle}>Contact Support</Text>
              </View>
              <View style={s.contactGrid}>
                <ContactCard
                  icon="✉"
                  title="Email Support"
                  subtitle="Detailed issues, billing, account problems"
                  cta="Send Email"
                  accentColor={C.gold}
                  onPress={()=>{}}
                  delay={710}
                />
                <ContactCard
                  icon="💬"
                  title="Live Chat"
                  subtitle="Quick questions, Mon–Fri 9am–6pm WAT"
                  cta="Start Chat"
                  accentColor={C.success}
                  onPress={()=>{}}
                  delay={760}
                />
              </View>
              <FadeSlide delay={800} style={s.whatsappCard}>
                <TouchableOpacity style={s.whatsappInner} activeOpacity={0.8} onPress={()=>{}}>
                  <View style={s.whatsappIconBox}>
                    <Text style={{fontSize:20}}>📱</Text>
                  </View>
                  <View style={{flex:1}}>
                    <Text style={s.whatsappTitle}>WhatsApp Support</Text>
                    <Text style={s.whatsappSub}>Message us on +234 800 000 0000 · Usually replies within 2 hours</Text>
                  </View>
                  <Text style={{color:C.gold,fontSize:18,fontWeight:'300',lineHeight:22}}>›</Text>
                </TouchableOpacity>
              </FadeSlide>
            </FadeSlide>

            {/* Response time notice */}
            <FadeSlide delay={840} style={s.responseNote}>
              <Text style={{fontSize:14}}>⏱</Text>
              <Text style={s.responseText}>
                Support is available Monday–Friday, 9am–6pm WAT. Emails are typically answered within 24 hours.
              </Text>
            </FadeSlide>

            {/* Community */}
            <FadeSlide delay={880} style={s.communityCard}>
              <View style={s.communityTop}>
                <Text style={s.communityIcon}>🌍</Text>
                <View>
                  <Text style={s.communityTitle}>Melanin Skin Community</Text>
                  <Text style={s.communitySub}>Join 12,000+ users sharing tips and progress</Text>
                </View>
              </View>
              <Text style={s.communityBody}>
                Share your skin journey, ask questions, and get advice from others with melanin-rich skin. Our moderated community is a safe space for honest skincare conversations.
              </Text>
              <TouchableOpacity style={s.communityBtn} onPress={()=>{}}>
                <Text style={s.communityBtnText}>Join the Community →</Text>
              </TouchableOpacity>
            </FadeSlide>

            {/* App info footer */}
            <FadeSlide delay={940} style={s.appInfo}>
              <Text style={s.appInfoText}>Melanin Scan  v1.0.0  ·  Build 100</Text>
              <Text style={s.appInfoSub}>Built for melanin-rich skin, by design.</Text>
            </FadeSlide>
          </>
        )}

        <View style={{ height:80 }}/>
      </ScrollView>
    </AfricanBG>
  );
}

const s = StyleSheet.create({
  scroll: { paddingTop:110,paddingHorizontal:22 },

  header:      { alignItems:'center',marginBottom:24 },
  helpBadge:   { width:58,height:58,borderRadius:16,backgroundColor:C.goldPale,borderWidth:1.5,borderColor:C.gold,alignItems:'center',justifyContent:'center',marginBottom:14,shadowColor:C.gold,shadowOpacity:0.35,shadowOffset:{width:0,height:0},shadowRadius:12,elevation:8 },
  helpBadgeIcon:{ color:C.gold,fontSize:24,fontWeight:'900' },
  title:       { color:C.cream,fontSize:28,fontWeight:'900',marginBottom:6 },
  subtitle:    { color:C.creamDim,fontSize:13,textAlign:'center',lineHeight:20,paddingHorizontal:16 },

  categoryScroll:{ marginBottom:20 },

  catHeader:   { flexDirection:'row',alignItems:'center',gap:14,marginBottom:16 },
  catIconBig:  { width:44,height:44,borderRadius:12,borderWidth:1,alignItems:'center',justifyContent:'center' },
  catTitle:    { color:C.cream,fontSize:17,fontWeight:'800',marginBottom:2 },
  catCount:    { color:C.creamDim,fontSize:11 },

  sectionWrap: { marginBottom:20 },
  sectionRow:  { flexDirection:'row',alignItems:'center',gap:8,marginBottom:14 },
  sectionBar:  { width:4,height:18,borderRadius:2,backgroundColor:C.gold },
  sectionTitle:{ color:C.cream,fontSize:17,fontWeight:'800' },

  contactGrid: { flexDirection:'row',gap:10,marginBottom:10 },

  whatsappCard:  { marginBottom:0 },
  whatsappInner: { flexDirection:'row',alignItems:'center',gap:14,backgroundColor:C.bgCard,borderWidth:1,borderColor:C.border,borderRadius:14,padding:14 },
  whatsappIconBox:{ width:42,height:42,borderRadius:10,backgroundColor:'rgba(93,190,138,0.12)',borderWidth:1,borderColor:'rgba(93,190,138,0.25)',alignItems:'center',justifyContent:'center' },
  whatsappTitle: { color:C.cream,fontSize:14,fontWeight:'700',marginBottom:3 },
  whatsappSub:   { color:C.creamDim,fontSize:11,lineHeight:16 },

  responseNote: { flexDirection:'row',gap:8,backgroundColor:'rgba(200,134,10,0.07)',borderWidth:1,borderColor:C.border,borderRadius:12,padding:13,marginTop:10,marginBottom:20,alignItems:'flex-start' },
  responseText: { flex:1,color:C.creamDim,fontSize:12,lineHeight:18 },

  communityCard:  { backgroundColor:C.bgCard,borderWidth:1,borderColor:C.border,borderRadius:16,padding:18,marginBottom:16 },
  communityTop:   { flexDirection:'row',alignItems:'center',gap:12,marginBottom:12 },
  communityIcon:  { fontSize:24 },
  communityTitle: { color:C.cream,fontSize:15,fontWeight:'800',marginBottom:2 },
  communitySub:   { color:C.creamDim,fontSize:11 },
  communityBody:  { color:C.creamDim,fontSize:13,lineHeight:20,marginBottom:14 },
  communityBtn:   { backgroundColor:C.goldPale,borderWidth:1,borderColor:C.border,borderRadius:10,paddingVertical:11,alignItems:'center' },
  communityBtnText:{ color:C.gold,fontSize:13,fontWeight:'700' },

  appInfo:     { alignItems:'center',paddingVertical:4 },
  appInfoText: { color:'rgba(200,134,10,0.30)',fontSize:10,fontWeight:'700',letterSpacing:1.5,marginBottom:4 },
  appInfoSub:  { color:'rgba(245,222,179,0.15)',fontSize:10 },

  searchResultsHeader:{ flexDirection:'row',alignItems:'center',gap:8,marginBottom:14 },
  searchResultsDot:   { width:5,height:5,borderRadius:2.5,backgroundColor:C.gold },
  searchResultsLabel: { color:C.creamDim,fontSize:13,fontWeight:'600' },
  searchCatLabel:     { marginBottom:6,marginTop:4 },

  noResults:     { alignItems:'center',paddingVertical:40 },
  noResultsIcon: { color:C.gold,fontSize:36,marginBottom:14 },
  noResultsTitle:{ color:C.cream,fontSize:18,fontWeight:'800',marginBottom:8 },
  noResultsText: { color:C.creamDim,fontSize:13,textAlign:'center',lineHeight:20,paddingHorizontal:24 },
});